// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// case_path_nonsmooth
Rcpp::List case_path_nonsmooth(arma::vec a, arma::mat B, arma::vec c, double lam, double alpha_0, double alpha_1, int j, double beta_0_w0, arma::vec beta_w0, arma::vec theta_w0);
RcppExport SEXP _NonsmoothPath_case_path_nonsmooth(SEXP aSEXP, SEXP BSEXP, SEXP cSEXP, SEXP lamSEXP, SEXP alpha_0SEXP, SEXP alpha_1SEXP, SEXP jSEXP, SEXP beta_0_w0SEXP, SEXP beta_w0SEXP, SEXP theta_w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_1(alpha_1SEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< double >::type beta_0_w0(beta_0_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_w0(beta_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_w0(theta_w0SEXP);
    rcpp_result_gen = Rcpp::wrap(case_path_nonsmooth(a, B, c, lam, alpha_0, alpha_1, j, beta_0_w0, beta_w0, theta_w0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NonsmoothPath_case_path_nonsmooth", (DL_FUNC) &_NonsmoothPath_case_path_nonsmooth, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_NonsmoothPath(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
