# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Case-weight adjusted solution path for L2 regularized nonsmooth problem (quantile regression and svm)
#'
#' @description
#' Path-following algorithm to exactly solve 
#' 	(beta_{0,w}, beta_{w}) = argmin_{beta_0, beta} \sum_{i \neq j} f(g_i(beta_0, beta)) + w*f(g_{j}(beta_0, beta)) + lambda / 2 * \|beta\|_2^2
#' for 0 <= w <= 1, where g_i(beta_0, beta) = a_i beta_0 + b_i^T beta + c_i and f(r) = alpha_0 max(r, 0) + alpha_1 max(-r, 0)
#'
#' @param a A \eqn{n \times 1} vector and a^T = (a_1, ..., a_n)
#' @param B A \eqn{n \times p} matrix and B^T = (b_1, ..., b_n)
#' @param c A \eqn{n \times 1} matrix and c^T = (b_1, ..., b_n) 
#' @param lam Regularization parameter for L2 penalty
#' @param alpha_0 A scalar in the definition of f(r)
#' @param alpha_1 A scalar in the definition of f(r)
#' @param j Index of the observation that is attached a weight
#' @param beta_0_w0 A scalar, which is the true value of beta_{0,w} when w = w_0 = 1
#' @param beta_w0 A \eqn{p \times 1} vector, which is the true value of beta_{w} when w = w_0 = 1
#' @param theta_w0 A \eqn{n \times 1} vector, which is the true value of the dual variable when w = w_0 = 1
#'
#' @details
#' This function will be called by function CaseInfluence_nonsmooth to generate case influence graph for each case.
#'
#' @return W_vec A list of breakout points
#' @return Beta_0 True values of beta_{0,w} at breakout points
#' @return Theta True values of theta_{w} at breakout points
#' @return Beta True values of beta_{w} at breakout points
case_path_nonsmooth <- function(a, B, c, lam, alpha_0, alpha_1, j, beta_0_w0, beta_w0, theta_w0) {
    .Call(`_pathNonsmooth_case_path_nonsmooth`, a, B, c, lam, alpha_0, alpha_1, j, beta_0_w0, beta_w0, theta_w0)
}

